name: publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: publish
        run: sh gradlew :Plugin:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
